apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: crud-app
type: Opaque
stringData:
  username: "#{DB_ADMIN_USERNAME}#"
  password: "#{DB_ADMIN_PASSWORD}#"
  database: "#{DB_NAME}#"
  host: "#{POSTGRES_FQDN}#"